### PR TITLE
Clean up tables when materialization isn´t incremental

### PR DESCRIPTION
**Pull request by datalytics1**
Minor change to adapters.sql logic to clean_up table when materialization isn´t incremental.

### CODE REVIEW

**Review by courentin — APPROVED** [review]

**Review by ojaved-equip — APPROVED** [review]

**Comment by owenprough-sift** [comment]
I tested these changes on my local project and they worked great. Thanks for making these changes!

**Comment by oriordanniall** [comment]
As this base is out of branch and has not been updated recently, I created a new PR that has been rebased: https://github.com/Tomme/dbt-athena/pull/72

**Comment by nialloriordan** [comment]
As this base is out of branch and has not been updated recently, I created a new PR that has been rebased: https://github.com/Tomme/dbt-athena/pull/73

**Comment by Gatsby-Lee** [comment]
@courentin 
Hi, I have a question about your change.
If the materialized is "table" and external_location is set, although the table is recreated, doesn't it make an error?

For example, since the external_location is set(static path),  although the table is recreated, creating a new table will fail.

what issue did you try to fix with this change?

**Comment by Gatsby-Lee** [comment]
@jessedobbelaere
Thank you for comment.
I built a macro that can generate unique externa_location per model.
BTW, even for a model, there could be a error due to the existing path in S3.
Therefore, I add random prefix on the S3.

I might miss sth to understand your change.
your change is 
```
  {% if config.get('incremental_strategy') == 'insert_overwrite' %}
```
```
  {% if config.get('incremental_strategy') != 'append' %}
```

doesn't `incremental_strategy' != 'append'` equal to `incremental_strategy' != 'insert_overwrite'`?

**Comment by jessedobbelaere** [comment]
Hi @Gatsby-Lee they're not my changes, but I believe the issue got introduced in https://github.com/Tomme/dbt-athena/pull/43/files

In the past, tables always got cleaned up. Since the changes in #43 the value of `incremental_strategy` is set to `NONE` when I log it, so the cleanup never happens by default anymore. It should only skip the cleanup in case it's an append strategy, so that's what the bugfix is about.

**Comment by Gatsby-Lee** [comment]
@jessedobbelaere got it.
so, it gives the same functionality, but it breaks the existing implantation. 

Thank you

**Comment by Tomme** [comment]
Resolved by #73, thank you for your contribution though!

**Comment by Gatsby-Lee** [comment]
thank you @jessedobbelaere @Tomme

**Pull request closed without merging**
