### PR TITLE
Support PyAthena above version 2.6.*

### PR DESCRIPTION
**Pull request by mederka**
- Fixes the `ParseException` raised by newer versions of PyAthena

- All integration tests passed

### CODE REVIEW

**Comment by owenprough-sift** [comment]
You may want to make some minor updates to your branch based on #71 recently merging into master.

**Comment by mederka** [comment]
Thanks for the heads-up, @owenprough-sift. I will reword this PR.

**Comment by Tomme** [comment]
👍

**Comment by Gatsby-Lee** [comment]
@mederka Thank you!!

**Pull request merged**
